cc_library(
    name = "sort",
    srcs = [
        "sort/bubble.c",
        "sort/bubble.h",
    ],
)

cc_library(
   name = "utils",
   srcs = [
       "utils/utils.c",
       "utils/utils.h",
   ],
)
